#! /bin/sh

# Mouse focusing
bspc config click_to_focus button1

# Desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# Window rules
bspc rule -a rofi manage=off

xsetroot -cursor_name left_ptr
xrdb ~/.Xresources
compton &
polybar top &
sxhkd &
