#!/bin/sh

if ! [[ -n $XDG_CONFIG_HOME ]]; then
   export XDG_CONFIG_HOME=$HOME/.config
fi

if ! [[ -n $XDG_DATA_HOME ]]; then
   export XDG_DATA_HOME=$HOME/.local/share
fi

# Create the config directory
CFG=$XDG_CONFIG_HOME/zsh
mkdir -p $CFG

# Create the data directory for shell themes
STD=$XDG_DATA_HOME/shell-themes
mkdir -p $STD

# Create the data directory for zgen and clone the zgen repo there
if [ ! -d $HOME/.zgen ]; then
    git clone https://github.com/tarjoilija/zgen.git $HOME/.zgen
fi

# Link with stow
stow . --target $CFG

# ZSH isn't compliant with XDG (witout editing ZDOTDIR in /etc/zshenv) - for my
# needs it's simpler to just link to where it expects
if [ ! -L $HOME/.zshrc ]; then
    ln -s $CFG/zshrc $HOME/.zshrc
fi

# Also link zprofile
if [ ! -L $HOME/.zprofile ]; then
    ln -s $CFG/zprofile $HOME/.zprofile
fi
