#!/bin/sh

# Create the config directory
CFG=$XDG_CONFIG_HOME/zsh
mkdir -p $CFG

# Create the data directory for shell themes
STD=$XDG_DATA_HOME/shell-themes
mkdir -p $STD
if [ ! -d $STD/the-one-theme ]; then
    git clone https://github.com/benniemosher/the-one-theme.git $STD/the-one-theme
fi

# Create the data directory for zgen and clone the zgen repo there
if [ ! -d $HOME/.zgen ]; then
    git clone https://github.com/tarjoilija/zgen.git $HOME/.zgen
fi

# Link with stow
stow . --target $CFG

# ZSH isn't compliant with XDG (witout editing ZDOTDIR in /etc/zshenv) - for my
# needs it's simpler to just link to where it expects
if [ ! -L $HOME/.zshrc ]; then
    ln -s $CFG/zshrc $HOME/.zshrc
fi

# Also link prezto
if [ ! -L $HOME/.zpreztorc ]; then
    ln -s $CFG/zpreztorc $HOME/.zpreztorc
fi
