#!/bin/sh

# Create the config directory
CFG=$XDG_CONFIG_HOME/zsh
mkdir -p $CFG

# Create the data directory for zgen and clone the zgen repo there
git clone https://github.com/tarjoilija/zgen.git $HOME/.zgen

# Link with stow
stow . --target $CFG

# ZSH isn't compliant with XDG (witout editing ZDOTDIR in /etc/zshenv) - for my
# needs it's simpler to just link to where it expects
ln -s $CFG/zshrc $HOME/.zshrc
