export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_BIN_HOME=$HOME/.local/bin

export PATH=$XDG_BIN_HOME:$PATH

# ZGen
# This needs to be in the home directory as it is technically honouring ZDOTDIR
# which is not always going to reflect XDG specs
export ZGEN_HOME="${HOME}/.zgen"

# CLV Script config
export CLV_ROOT="${ZGEN_HOME}/cleversoap/clv-master"

source "${ZGEN_HOME}/zgen.zsh"

if ! zgen saved; then

    # Prezto - important to note that these must also be configured
    # in ~/.zpreztorc otherwise zgen won't load them properly
    zgen prezto
    zgen prezto git
    zgen prezto syntax-highlighting
    zgen prezto history-substring-search

    # Pure
    zgen load mafredri/zsh-async
    zgen load sindresorhus/pure

    # CLV
    zgen load cleversoap/clv

    # Save init.zsh for immediate startup next time
    zgen save

fi

# Base16 Shell
BASE16_SHELL=$XDG_DATA_HOME/shell-themes/base16/scripts/base16-oceanicnext.sh
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Causes issues with globs in zgen
unsetopt nocaseglob
unsetopt extendedglob

# clv needs to be autoloaded
autoload -U clv

# Setup environments
export ENV_HOME="${XDG_DATA_HOME}/env"

if [ -d $ENV_HOME ]; then
    export CLV_ENVS=(`for i in $(ls -d $ENV_HOME/*); do basename $i; done`)

    # Some plugins require extra init steps, they are checked for and added
    cei_plugins=()

    # If the pyenv-virtualenv plugin exists
    if [ -d $ENV_HOME/pyenv/plugins/pyenv-virtualenv ]; then
        cei_plugins+="pyenv virtualenv-init"
    fi

    # Call the plugin inits
    export CLV_ENVS_INIT_PLUGINS=$cei_plugins

    # Initialise all environments and plugins
    clv env init
fi

# Setup prompt
autoload -U promptinit && promptinit
prompt pure
