export SHELL=`which zsh`

if [ -d $ENV_HOME ]; then
    export CLV_ENVS=(`for i in $(ls -d $ENV_HOME/*); do basename $i; done`)
fi

# Source it again so that zgen will pickup changes from zgen saved
source "${ZGEN_HOME}/zgen.zsh"

export HISTFILE=$HOME/.zhistory
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE
setopt inc_append_history
setopt share_history

# Causes issues with globs in zgen
unsetopt nocaseglob
unsetopt extendedglob

# Setup prompt
export PURE_PROMPT_SYMBOL='λ'
set PROMPT_SUBST

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey "\e[A" history-substring-search-up
bindkey "\e[B" history-substring-search-down
bindkey "^Xz" zce

# Handle shell titles - prints the user name and directory or directory
# and currently running process in the title
export precmd () { print -Pn "\e]2;%n | ${PWD##*/}\a" }
precmd_functions+=precmd

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if [ -e $HOME/.zshlocal ]; then
    source "$HOME/.zshlocal"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
